### ISSUE TITLE
cy.OpenTab()

### ISSUE THREAD

**Issue by vernko** [ElSnoMan/cyleniumio#85]

**Comment by ElSnoMan** [comment]
@vernko What is this function supposed to do? Is it supposed to open a new, empty tab?

**Comment by vernko** [comment]
Yeah just open a new tab. I didn't know if we'd need this or not. Or maybe like a switchTab() or something.

**Comment by ElSnoMan** [comment]
I don't think we need an `OpenTab()` function, but a `SwitchTo()` would be very valuable. There are a few things we need to be able to switch to

- [] Tab
- [] Window
- [] iframe
